#!/bin/bash

sudo apt install -y bc
sudo apt install -y g++
sudo apt install -y git
sudo apt install -y mpi
sudo apt install -y tar
sudo apt install -y zip
sudo apt install -y gcc
sudo apt install -y npm
sudo apt install -y make
sudo apt install -y wget
sudo apt install -y curl
sudo apt install -y ergo
sudo apt install -y psi4
sudo apt install -y mpqc
sudo apt install -y gzip
sudo apt install -y tcsh
sudo apt install -y flex
sudo apt install -y mopac
sudo apt install -y cmake
sudo apt install -y mpich
sudo apt install -y fftw2
sudo apt install -y pngnq
sudo apt install -y bison
sudo apt install -y patch
sudo apt install -y unrar
sudo apt install -y nwchem
sudo apt install -y gthumb
sudo apt install -y png23d
sudo apt install -y ffmpeg
sudo apt install -y zlib1g
sudo apt install -y chktex
sudo apt install -y golang
sudo apt install -y nodejs
sudo apt install -y flatpak
sudo apt install -y pngmeta
sudo apt install -y python3
sudo apt install -y calibre
sudo apt install -y libnss3
sudo apt install -y numlockx
sudo apt install -y automake
sudo apt install -y fftw-dev
sudo apt install -y png2html
sudo apt install -y pngcheck
sudo apt install -y pngcrush
sudo apt install -y pngquant
sudo apt install -y pngtools
sudo apt install -y ffmpegfs
sudo apt install -y libzstd1
sudo apt install -y libblas3
sudo apt install -y libbliss
sudo apt install -y gfortran
sudo apt install -y xorg-dev
sudo apt install -y libz-dev
sudo apt install -y libjpeg62
sudo apt install -y libbliss2
sudo apt install -y gedit-dev
sudo apt install -y libxt-dev
sudo apt install -y golang-go
sudo apt install -y openbabel
sudo apt install -y libgtk-3-0
sudo apt install -y gzip-win32
sudo apt install -y libpng-dev
sudo apt install -y ffmpeg-doc
sudo apt install -y zlib1g-dev
sudo apt install -y liblapack3
sudo apt install -y liblapacke
sudo apt install -y vokoscreen
sudo apt install -y libbz2-dev
sudo apt install -y libx11-dev
sudo apt install -y libxpm-dev
sudo apt install -y openmpi-bin
sudo apt install -y libopenmpi3
sudo apt install -y libjpeg-dev
sudo apt install -y libpng16-16
sudo apt install -y libpnglite0
sudo apt install -y python3-dev
sudo apt install -y libzstd-dev
sudo apt install -y libblas-dev
sudo apt install -y libblas64-3
sudo apt install -y libblis-dev
sudo apt install -y libkim-api2
sudo apt install -y default-jre
sudo apt install -y default-jdk
sudo apt install -y fftw2-single
sudo apt install -y fftw2-double
sudo apt install -y libfftw3-bin
sudo apt install -y libfftw3-dev
sudo apt install -y libpng++-dev
sudo apt install -y libpng-tools
sudo apt install -y ffmpegthumbs
sudo apt install -y liblapacke64
sudo apt install -y libblas-test
sudo apt install -y libblasr-dev
sudo apt install -y libbliss-dev
sudo apt install -y gedit-common
sudo apt install -y openbabel-gui
sudo apt install -y libfftw3-mpi3
sudo apt install -y libjpeg-progs
sudo apt install -y libjpeg-tools
sudo apt install -y python3-adios
sudo apt install -y liblapack-dev
sudo apt install -y liblapack-doc
sudo apt install -y liblapack64-3
sudo apt install -y libblas64-dev
sudo apt install -y libblis64-dev
sudo apt install -y gedit-plugins
sudo apt install -y libgtk2.0-dev
sudo apt install -y libatk1.0-dev
sudo apt install -y libcairo2-dev
sudo apt install -y mono-complete
sudo apt install -y libkim-api-dev
sudo apt install -y libkim-api-doc
sudo apt install -y openkim-models
sudo apt install -y openmpi-common
sudo apt install -y libopenmpi-dev
sudo apt install -y libfftw3-long3
sudo apt install -y libfftw3-quad3
sudo apt install -y libpnglite-dev
sudo apt install -y liblapack-test
sudo apt install -y liblapacke-dev
sudo apt install -y libblas64-test
sudo apt install -y openkim-models
sudo apt install -y openssh-client
sudo apt install -y mpi-default-bin
sudo apt install -y mpi-default-dev
sudo apt install -y fftw-single-dev
sudo apt install -y fftw-double-dev
sudo apt install -y liblapack64-dev
sudo apt install -y exuberant-ctags
sudo apt install -y libncurses5-dev
sudo apt install -y build-essential
sudo apt install -y libfftw3-double3
sudo apt install -y libfftw3-mpi-dev
sudo apt install -y libfftw3-single3
sudo apt install -y libturbojpeg-dev
sudo apt install -y liblapack64-test
sudo apt install -y liblapacke64-dev
sudo apt install -y gedit-plugin-git
sudo apt install -y libturbojpeg0-dev
sudo apt install -y ffmpegthumbnailer
sudo apt install -y libadios-mpich-dev
sudo apt install -y libblis-openmp-dev
sudo apt install -y libblis-serial-dev
sudo apt install -y gedit-latex-plugin
sudo apt install -y libjpeg-turbo-progs
sudo apt install -y libblis-pthread-dev
sudo apt install -y libbliss-dev-common
sudo apt install -y png-definitive-guide
sudo apt install -y libadios-openmpi-dev
sudo apt install -y libblis64-openmp-dev
sudo apt install -y libblis64-serial-dev
sudo apt install -y libblis64-pthread-dev
sudo apt install -y gedit-plugin-terminal
sudo apt install -y gedit-plugin-bookmarks
sudo apt install -y gedit-plugin-text-size
sudo apt install -y gedit-plugin-join-lines
sudo apt install -y gedit-plugin-multi-edit
sudo apt install -y gedit-plugin-draw-spaces
sudo apt install -y gedit-plugin-code-comment
sudo apt install -y gedit-plugin-color-picker
sudo apt install -y gedit-plugin-smart-spaces
sudo apt install -y gedit-plugin-character-map
sudo apt install -y gedit-plugin-session-saver
sudo apt install -y gedit-plugin-word-completion
sudo apt install -y gnome-software-plugin-flatpak
sudo apt install -y gedit-plugin-bracket-completion
sudo apt install -y gedit-source-code-browser-plugin
